version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  node_app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      MONGO_USERNAME: admin
      MONGO_PASSWORD: password
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: order_system
    depends_on:
      - mongodb
    volumes:
      - .:/order_system
      - /order_system/node_modules
    command: npm start

volumes:
  mongodb_data: